version: '3.9'

services:
  qdrant_node1:
    image: qdrant/qdrant:latest
    container_name: qdrant_node1
    volumes:
      - qdrant_data1:/qdrant/storage
    ports:
      - "6333:6333"
      - "6334:6334"
      - "6335:6335"
    environment:
      QDRANT__CLUSTER__ENABLED: "true"
      QDRANT__LOG_LEVEL: "INFO"
      QDRANT__SERVICE__HTTP_PORT: "6333"
      QDRANT__SERVICE__GRPC_PORT: "6334"
      QDRANT__CLUSTER__P2P__PORT: "6335"
    command: "./qdrant --uri http://qdrant_node1:6335"
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  qdrant_node2:
    image: qdrant/qdrant:latest
    container_name: qdrant_node2
    volumes:
      - qdrant_data2:/qdrant/storage
    depends_on:
      - qdrant_node1
    ports:
      - "6336:6333"
      - "6337:6334"
      - "6338:6335"
    environment:
      QDRANT__CLUSTER__ENABLED: "true"
      QDRANT__LOG_LEVEL: "INFO"
      QDRANT__SERVICE__HTTP_PORT: "6333"
      QDRANT__SERVICE__GRPC_PORT: "6334"
      QDRANT__CLUSTER__P2P__PORT: "6335"
    command: "./qdrant --bootstrap http://qdrant_node1:6335 --uri http://qdrant_node2:6335"
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

volumes:
  qdrant_data1:
    name: qdrant_data1
  qdrant_data2:
    name: qdrant_data2

networks:
  default:
    name: qdrant_network
    driver: bridge
